{
 "title": "Simple ClickHouse OTel Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "ClickHouse instance", "query": "clickhouse-datasource-oauth2" },
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": "SELECT DISTINCT ServiceName FROM otel_traces"
   },
   {
    "name": "trace_id",
    "label": "Trace Id",
    "query": "SELECT DISTINCT TraceId FROM otel_traces WHERE ParentSpanId = '' LIMIT 100"
   }
  ]
 },
 "panels": [
  { "title": "Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traces per Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  ServiceName,\r\n  count() as ` `\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\nGROUP BY ServiceName, time\r\nORDER BY time ASC\r\nLIMIT 100000\r\n"
    }
   ]
  },
  {
   "title": "Service Performance - p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  ServiceName,\r\n  quantile(0.99)(Duration)/1000000 AS p99\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ( Timestamp  >= $__fromTime AND Timestamp <= $__toTime )\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\nGROUP BY time, ServiceName\r\nORDER BY time ASC\r\nLIMIT 100000\r\n"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeInterval(Timestamp) as time,\r\n  count(*) as ` `,\r\n  ServiceName\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND $__timeFilter(Timestamp)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n AND StatusCode IN ('Error', 'STATUS_CODE_ERROR')\r\n  AND ServiceName != 'loadgenerator' GROUP BY ServiceName, time\r\nORDER BY time ASC\r\nLIMIT 100000"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  min(Timestamp) as timestamp,\r\n  TraceId as `Trace ID`,\r\n  argMin(ServiceName, Timestamp) as `Service Name`,\r\n  divide(max(Duration), 1000000) as Duration\r\nFROM otel_traces\r\nWHERE\r\n  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)\r\n  AND ServiceName IN (${serviceName:singlequote})\r\n  AND ServiceName != 'loadgenerator'\r\n  AND $__timeFilter(Timestamp)\r\nGROUP BY TraceId\r\nORDER BY Duration DESC\r\nLIMIT 100\r\n"
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "traces",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH '${trace_id}' as trace_id, (SELECT min(Start) FROM \"otel_traces_trace_id_ts\" WHERE TraceId = trace_id) as trace_start, (SELECT max(End) + 1 FROM \"otel_traces_trace_id_ts\" WHERE TraceId = trace_id) as trace_end SELECT \"TraceId\" as traceID, \"SpanId\" as spanID, \"ParentSpanId\" as parentSpanID, \"ServiceName\" as serviceName, \"SpanName\" as operationName, \"Timestamp\" as startTime, multiply(\"Duration\", 0.000001) as duration, arrayMap(key -> map('key', key, 'value',\"SpanAttributes\"[key]), mapKeys(\"SpanAttributes\")) as tags, arrayMap(key -> map('key', key, 'value',\"ResourceAttributes\"[key]), mapKeys(\"ResourceAttributes\")) as serviceTags FROM \"otel_traces\" WHERE traceID = trace_id AND startTime >= trace_start AND startTime <= trace_end AND ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND ( Duration > 0 ) ORDER BY Timestamp DESC, Duration DESC LIMIT 1000"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Trace Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as timestamp, Body as body, SeverityText as level FROM \"otel_logs\" LIMIT 1000"
    }
   ]
  }
 ]
}