name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'release-*'

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - name: Cancel Previous Workflow Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on:
      - self-hosted
      - Linux
      - kube-common-test

    name: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
            [registry."docker.io"]
              mirrors = ["registry.deeplay.io/proxy-cache"]

      - name: Login to Deeplay Registry
        uses: docker/login-action@v2
        with:
          registry: registry.deeplay.io
          username: ${{ secrets.DOCKER_USERNAME_DEEPLAY }}
          password: ${{ secrets.DOCKER_PASSWORD_DEEPLAY }}

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.deeplay.io/infra/grafana
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value={{branch}}-{{sha}},enable={{is_default_branch}}
            type=raw,value={{tag}},event=tag
            type=sha,prefix={{branch}}-,enable=${{ !startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=registry.deeplay.io/ci-cache/grafana
          cache-to: type=registry,ref=registry.deeplay.io/ci-cache/grafana:cache,image-manifest=true,oci-mediatypes=true,mode=max

  # Пустая джоба, которая завершается после завершения всех required джоб.
  # Нужна для того, чтобы в branch protection не надо было указывать все билды
  # из матрицы по одному как required.
  success:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - run: echo "Done"
