on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from plugin.json
        id: plugin_version
        run: |
          VERSION=$(jq -r '.info.version' grafana-clickhouse-datasource/plugin.json)
          echo "version=$GRAFANA_CLICKHOUSE_VERSION" >> $GITHUB_OUTPUT

      - name: Create zip archive
        run: |
          zip -r grafana-clickhouse-datasource-$GRAFANA_CLICKHOUSE_VERSION.zip grafana-clickhouse-datasource

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: grafana-clickhouse-datasource-$GRAFANA_CLICKHOUSE_VERSION.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
